import { execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

// BRAWUKA-770 (follow-up to the BRAWUKA-764 incident): Docker snapshots the host
// /etc/resolv.conf into every container's embedded resolver at creation time and
// never refills a running container. When dhcpcd regenerated the host file during
// the n150 WiFi outage with no DHCP nameserver, every container created in that
// window was stuck on "NO EXTERNAL NAMESERVERS DEFINED" — staging deploys stopped
// for ~19h and web→POI answered 502. The durable fix is the Owner-selected policy
// (DHCP nameservers first, 1.1.1.1 appended as fallback) written to
// /etc/resolv.conf.tail, which the dhcpcd resolv.conf hook appends to every file
// it regenerates.
//
// Every case below runs the real scripts against a scratch `SYSROOT` tree with a
// PATH shim, so the assertions are about what the scripts do to host files and
// how they exit — never about this machine's own /etc/resolv.conf, and never
// about a live outage. The dhcpcd hook itself is mirrored in a fixture (see
// DHCPCD_HOOK_MIRROR) rather than executed from the host.
const REPO_ROOT = path.resolve(__dirname, "../../..");
// Each case runs a byte-identical copy of the scripts inside a scratch tree, so
// a run can never reach the real host paths or this machine's own /etc.
const SCRATCH_ROOT = "repo";
const DNS_SCRIPT = `${SCRATCH_ROOT}/scripts/devops/dns-fallback.sh`;
const PROVISION_SCRIPT = `${SCRATCH_ROOT}/scripts/devops/provision-vps.sh`;
const SCRIPT_SOURCES = [
  "scripts/devops/dns-fallback.sh",
  "scripts/devops/provision-vps.sh",
];
const FALLBACK_LINE = "nameserver 1.1.1.1";

// A faithful mirror of the dhcpcd-base 10.1.0 hook that owns /etc/resolv.conf on
// n150 (/usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf, build_resolv_conf): it writes
// the header, the DHCP nameserver block, and then /etc/resolv.conf.tail — and the
// tail is appended by the same assembly even when the DHCP block is empty, which
// is the property this whole contract rests on. Verified against the host's hook
// source, not inferred from the incident.
const DHCPCD_HOOK_MIRROR = `#!/usr/bin/env bash
# usage: <dest-resolv.conf> <dhcp-nameserver-lines> <tail-file>
set -euo pipefail
dest="$1"; servers="$2"; tail="$3"
{
  echo "# Generated by dhcpcd from wlp1s0.dhcp"
  printf '%s' "$servers"
  if [ -f "$tail" ]; then
    cat "$tail"
  else
    echo "# /etc/resolv.conf.tail can replace this line"
  fi
} > "$dest"
`;

let tmpRoot = "";
let stubBin = "";
let runIndex = 0;

beforeAll(() => {
  tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "coffeemode-dns-fallback-"));
  stubBin = path.join(tmpRoot, "bin");
  fs.mkdirSync(stubBin);
  fs.mkdirSync(path.join(tmpRoot, "home"));
  for (const source of SCRIPT_SOURCES) {
    const target = path.join(tmpRoot, SCRATCH_ROOT, source);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(path.join(REPO_ROOT, source), target);
  }
  fs.writeFileSync(
    path.join(stubBin, "apt-get"),
    '#!/usr/bin/env bash\nprintf \'apt-get %s\\n\' "$*" >> "$STUB_LOG"\n',
    { mode: 0o755 },
  );
  fs.writeFileSync(
    path.join(stubBin, "id"),
    '#!/usr/bin/env bash\ncase "$*" in -u) echo 0 ;; *) exec /usr/bin/id "$@" ;; esac\n',
    { mode: 0o755 },
  );
  fs.writeFileSync(
    path.join(stubBin, "curl"),
    '#!/usr/bin/env bash\nprintf \'curl %s\\n\' "$*" >> "$STUB_LOG"\nprintf \'203.0.113.10\\n\'\n',
    { mode: 0o755 },
  );
  fs.writeFileSync(
    path.join(stubBin, "docker"),
    '#!/usr/bin/env bash\ncase "$*" in\n  --version) echo "Docker version 27.0.0-stub, build stub" ;;\n  info*) echo "active" ;;\n  *) echo "stub" ;;\nesac\n',
    { mode: 0o755 },
  );
});

afterAll(() => {
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

interface ScriptRun {
  status: number;
  output: string;
  invocations: string;
}

const CLEARED_ENV: Record<string, undefined> = {
  SYSROOT: undefined,
  DNS_FALLBACK_NAMESERVER: undefined,
};

function run(
  script: string,
  args: string[],
  overrides: Record<string, string | undefined> = {},
): ScriptRun {
  runIndex += 1;
  const logPath = path.join(tmpRoot, `invocations-${runIndex}.log`);
  fs.writeFileSync(logPath, "");
  const env: NodeJS.ProcessEnv = { ...process.env };
  for (const [key, value] of Object.entries({
    ...CLEARED_ENV,
    STUB_LOG: logPath,
    ...overrides,
  })) {
    if (value === undefined) delete env[key];
    else env[key] = value;
  }
  env.PATH = `${stubBin}:${env.PATH ?? ""}`;
  env.HOME = path.join(tmpRoot, "home");

  let status = 0;
  let output = "";
  try {
    output = execSync(`bash "${path.join(tmpRoot, script)}" ${args.join(" ")}`, {
      encoding: "utf8",
      env,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    const failure = error as { status?: number; stdout?: string; stderr?: string };
    status = failure.status ?? -1;
    output = `${failure.stdout ?? ""}${failure.stderr ?? ""}`;
  }
  return { status, output, invocations: fs.readFileSync(logPath, "utf8") };
}

interface HostFixture {
  root: string;
  resolvConf: string;
  tailFile: string;
  hook: string;
}

// Builds a scratch host tree. Defaults to the n150 shape: a dhcpcd-owned regular
// /etc/resolv.conf and the resolv.conf hook that appends /etc/resolv.conf.tail.
function makeHost(options: {
  resolvConf?: string | null;
  resolvConfSymlink?: string;
  tail?: string;
  hook?: string | null;
} = {}): HostFixture {
  const root = fs.mkdtempSync(path.join(tmpRoot, "host-"));
  const etc = path.join(root, "etc");
  fs.mkdirSync(etc, { recursive: true });
  const resolvConf = path.join(etc, "resolv.conf");
  const tailFile = path.join(etc, "resolv.conf.tail");
  const hook = path.join(root, "usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf");

  if (options.resolvConfSymlink) {
    fs.symlinkSync(options.resolvConfSymlink, resolvConf);
  } else if (options.resolvConf !== null) {
    fs.writeFileSync(
      resolvConf,
      options.resolvConf ??
        "# Generated by dhcpcd from wlp1s0.dhcp, wlp1s0.dhcp6\nnameserver 192.168.5.1\n",
    );
  }
  if (options.tail !== undefined) fs.writeFileSync(tailFile, options.tail);
  if (options.hook !== null) {
    fs.mkdirSync(path.dirname(hook), { recursive: true });
    fs.writeFileSync(
      hook,
      options.hook ??
        `# dhcpcd-base 10.1.0 resolv.conf hook\nif [ -f /etc/resolv.conf.tail ]; then\n\tcat /etc/resolv.conf.tail >> "$cf"\nfi\n`,
    );
  }
  return { root, resolvConf, tailFile, hook };
}

describe("Host DNS fallback (BRAWUKA-770)", () => {
  it("installs the fallback tail on a dhcpcd host without touching the live file", () => {
    const host = makeHost();
    const liveBefore = fs.readFileSync(host.resolvConf, "utf8");

    const result = run(DNS_SCRIPT, ["apply"], { SYSROOT: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("dns-fallback: ok");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
    // The DHCP entries stay first and untouched: the fallback is appended to the
    // file dhcpcd regenerates, never written over the live resolver config.
    expect(fs.readFileSync(host.resolvConf, "utf8")).toBe(liveBefore);
  });

  it("is idempotent: a re-run appends nothing and preserves other tail entries", () => {
    const host = makeHost({ tail: "nameserver 9.9.9.9\n" });

    const first = run(DNS_SCRIPT, ["apply"], { SYSROOT: host.root });
    const afterFirst = fs.readFileSync(host.tailFile, "utf8");
    const second = run(DNS_SCRIPT, ["apply"], { SYSROOT: host.root });

    expect(first.status).toBe(0);
    expect(second.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(afterFirst);
    expect(afterFirst).toBe(`nameserver 9.9.9.9\n${FALLBACK_LINE}\n`);
    expect(second.output).toContain("already carries");
  });

  it("writes nothing under --dry-run", () => {
    const host = makeHost();

    const result = run(DNS_SCRIPT, ["apply", "--dry-run"], { SYSROOT: host.root });

    expect(result.status).toBe(0);
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("keeps the snapshot non-empty in the outage window that broke BRAWUKA-764", () => {
    // The incident shape: dhcpcd regenerates while the link is down, so the DHCP
    // block is empty. Without the tail the regenerated host file has no
    // nameserver at all, and any container created then snapshots that emptiness.
    const host = makeHost({ resolvConf: "" });
    const mirror = path.join(tmpRoot, "20-resolv.conf.mirror");
    fs.writeFileSync(mirror, DHCPCD_HOOK_MIRROR, { mode: 0o755 });

    // Control: no fallback installed yet — the failure mode is reproducible.
    execSync(`bash "${mirror}" "${host.resolvConf}" "" "${host.tailFile}"`);
    expect(fs.readFileSync(host.resolvConf, "utf8")).not.toContain("nameserver");

    const applied = run(DNS_SCRIPT, ["apply"], { SYSROOT: host.root });
    execSync(`bash "${mirror}" "${host.resolvConf}" "" "${host.tailFile}"`);

    expect(applied.status).toBe(0);
    expect(applied.output).toContain("no nameserver line");
    // Same empty DHCP block, but the tail now keeps the file usable — this is the
    // guarantee, proven through the hook's own assembly order.
    expect(fs.readFileSync(host.resolvConf, "utf8")).toContain(FALLBACK_LINE);
  });

  it("reports a missing fallback as a failure, and passes once it is installed", () => {
    const host = makeHost();

    const before = run(DNS_SCRIPT, ["check"], { SYSROOT: host.root });
    expect(before.status).toBe(1);
    expect(before.output).toContain("dns-fallback: fail");
    expect(before.output).toContain("dns-fallback.sh apply");

    expect(run(DNS_SCRIPT, ["apply"], { SYSROOT: host.root }).status).toBe(0);

    const after = run(DNS_SCRIPT, ["check"], { SYSROOT: host.root });
    expect(after.status).toBe(0);
    expect(after.output).toContain("dns-fallback: ok");
    expect(after.output).toContain(FALLBACK_LINE);
  });

  it("fails the check while the live resolver file has no nameserver line", () => {
    // Tail installed, but the live file is still empty: a container created right
    // now would snapshot an empty upstream set, so the check must not pass.
    const host = makeHost({ resolvConf: "", tail: `${FALLBACK_LINE}\n` });

    const result = run(DNS_SCRIPT, ["check"], { SYSROOT: host.root });

    expect(result.status).toBe(1);
    expect(result.output).toContain("dns-fallback: fail");
    expect(result.output).toContain("dhcpcd");
    // The operator distinction that cost the incident its 19h: recreate containers
    // that already snapshotted the broken set instead of waiting.
    expect(result.output).toContain("recreate");
  });

  it("skips hosts whose resolver is not dhcpcd-managed, writing nothing", () => {
    const cases: Array<[string, HostFixture]> = [
      [
        "systemd-resolved stub symlink",
        makeHost({ resolvConfSymlink: "/run/systemd/resolve/stub-resolv.conf" }),
      ],
      ["no dhcpcd hook", makeHost({ hook: null })],
      [
        "dhcpcd hook that never reads the tail file",
        makeHost({
          hook: '#!/usr/bin/env bash\n# writes the DHCP nameservers and ignores any tail file\nprintf \'nameserver %s\\n\' "$new_domain_name_servers" > "$cf"\n',
        }),
      ],
    ];

    for (const [label, host] of cases) {
      const result = run(DNS_SCRIPT, ["apply"], { SYSROOT: host.root });
      expect(result.status, label).toBe(0);
      expect(result.output, label).toContain("dns-fallback: not-applicable");
      expect(fs.existsSync(host.tailFile), label).toBe(false);
    }
  });

  it("skips a host where openresolv's resolvconf owns the resolver", () => {
    const host = makeHost();
    const bin = path.join(tmpRoot, "resolvconf-bin");
    fs.mkdirSync(bin, { recursive: true });
    fs.writeFileSync(path.join(bin, "resolvconf"), "#!/usr/bin/env bash\nexit 0\n", {
      mode: 0o755,
    });

    const result = run(DNS_SCRIPT, ["apply"], {
      SYSROOT: host.root,
      PATH: `${bin}:${process.env.PATH ?? ""}`,
    });

    expect(result.status).toBe(0);
    expect(result.output).toContain("dns-fallback: not-applicable");
    expect(result.output).toContain("resolvconf");
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("revert removes only the fallback line and stays idempotent", () => {
    const host = makeHost({ tail: `nameserver 9.9.9.9\n${FALLBACK_LINE}\n` });

    const first = run(DNS_SCRIPT, ["revert"], { SYSROOT: host.root });
    expect(first.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe("nameserver 9.9.9.9\n");

    const second = run(DNS_SCRIPT, ["revert"], { SYSROOT: host.root });
    expect(second.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe("nameserver 9.9.9.9\n");
  });

  it("revert deletes the tail file when it held nothing else", () => {
    const host = makeHost({ tail: `${FALLBACK_LINE}\n` });

    expect(run(DNS_SCRIPT, ["revert"], { SYSROOT: host.root }).status).toBe(0);
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("requires a command instead of guessing one", () => {
    const result = run(DNS_SCRIPT, []);

    expect(result.status).toBe(2);
    expect(result.output).toContain("apply");
    expect(result.output).toContain("check");
    expect(result.output).toContain("revert");
  });
});

describe("Provisioning contract for the DNS fallback (BRAWUKA-770)", () => {
  const PROVISION_ARGS = ["--skip-swap", "--skip-ufw", "--skip-fail2ban", "--skip-dokploy"];

  it("applies the fallback on a fresh host with no Docker installed", () => {
    const host = makeHost();

    const result = run(PROVISION_SCRIPT, ["--skip-docker", ...PROVISION_ARGS], { SYSROOT: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("Step 4/8");
    expect(result.output).toContain("Host DNS fallback: dns-fallback: ok");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
    // Nothing else on the host was touched: Docker is skipped, so its daemon
    // config and the live resolver file stay exactly as they were.
    expect(fs.existsSync(path.join(host.root, "etc/docker/daemon.json"))).toBe(false);
    expect(fs.readFileSync(host.resolvConf, "utf8")).not.toContain(FALLBACK_LINE);
  });

  it("applies the fallback on a host that already has Docker installed", () => {
    // The BRAWUKA-764 host: Docker was installed long before, so the installer's
    // own branch never ran — the guarantee must not live inside it.
    const host = makeHost();

    const result = run(PROVISION_SCRIPT, PROVISION_ARGS, { SYSROOT: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("Docker is already installed");
    expect(result.output).toContain("Host DNS fallback: dns-fallback: ok");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
  });

  it("re-running provisioning does not duplicate the fallback entry", () => {
    const host = makeHost();

    run(PROVISION_SCRIPT, PROVISION_ARGS, { SYSROOT: host.root });
    const afterFirst = fs.readFileSync(host.tailFile, "utf8");
    const second = run(PROVISION_SCRIPT, PROVISION_ARGS, { SYSROOT: host.root });

    expect(second.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(afterFirst);
    expect(afterFirst.match(/nameserver 1\.1\.1\.1/g)).toHaveLength(1);
  });

  it("honours --skip-dns", () => {
    const host = makeHost();

    const result = run(PROVISION_SCRIPT, ["--skip-dns", ...PROVISION_ARGS], { SYSROOT: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("Host DNS fallback skipped (--skip-dns)");
    expect(result.output).toContain("Host DNS fallback: Skipped (--skip-dns)");
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });
});
