import { execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

// BRAWUKA-770 (follow-up to the BRAWUKA-764 incident): Docker snapshots the host
// /etc/resolv.conf into every container's embedded resolver at creation time and
// never refills a running container. When dhcpcd regenerated the host file during
// the n150 WiFi outage with no DHCP nameserver, every container created in that
// window was stuck on "NO EXTERNAL NAMESERVERS DEFINED" — staging deploys stopped
// for ~19h and web→POI answered 502. The durable fix is the Owner-selected policy
// (DHCP nameservers first, 1.1.1.1 appended as fallback) written to
// /etc/resolv.conf.tail, which the dhcpcd resolv.conf hook appends to every file
// it regenerates.
//
// Every case below runs the real scripts against a scratch `SYSROOT` tree with a
// hermetic PATH, so the assertions are about what the scripts do to host files
// and how they exit — never about this machine's own /etc/resolv.conf, never
// about a live outage, and never about whatever a CI runner happens to have
// installed (the GitHub Ubuntu image ships `resolvconf`, which would otherwise
// flip the detection branch the fixtures assert on). The dhcpcd hook itself is
// mirrored in a fixture (see DHCPCD_HOOK_MIRROR) rather than executed from the
// host.
const REPO_ROOT = path.resolve(__dirname, "../../..");
// Each case runs a byte-identical copy of the scripts inside a scratch tree, so
// a run can never reach the real host paths or this machine's own /etc.
const SCRATCH_ROOT = "repo";
const DNS_SCRIPT = `${SCRATCH_ROOT}/scripts/devops/dns-fallback.sh`;
const PROVISION_SCRIPT = `${SCRATCH_ROOT}/scripts/devops/provision-vps.sh`;
const SCRIPT_SOURCES = [
  "scripts/devops/dns-fallback.sh",
  "scripts/devops/provision-vps.sh",
];
const FALLBACK_LINE = "nameserver 1.1.1.1";
// dhcpcd stamps its own signature as the first line of every file it generates,
// including the ones it rebuilds with no nameserver. It is the ownership evidence
// the script requires before it writes anything (BRAWUKA-778).
const DHCPCD_SIGNATURE = "# Generated by dhcpcd from wlp1s0.dhcp, wlp1s0.dhcp6";

// The host tools the scripts under test resolve through PATH. The fixture supplies
// its own copies so detection cannot depend on the machine running the suite.
const SANDBOX_TOOLS = [
  "bash",
  "cat",
  "dirname",
  "grep",
  "head",
  "tail",
  "mkdir",
  "mktemp",
  "rm",
  "tr",
  "readlink",
  "sed",
  "awk",
];

// A faithful mirror of the dhcpcd-base 10.1.0 hook that owns /etc/resolv.conf on
// n150 (/usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf, build_resolv_conf): it writes
// the header, the DHCP nameserver block, and then /etc/resolv.conf.tail — and the
// tail is appended by the same assembly even when the DHCP block is empty, which
// is the property this whole contract rests on. Verified against the host's hook
// source, not inferred from the incident.
const DHCPCD_HOOK_MIRROR = `#!/usr/bin/env bash
# usage: <dest-resolv.conf> <dhcp-nameserver-lines> <tail-file>
set -euo pipefail
dest="$1"; servers="$2"; tail="$3"
{
  echo "# Generated by dhcpcd from wlp1s0.dhcp"
  printf '%s' "$servers"
  if [ -f "$tail" ]; then
    cat "$tail"
  else
    echo "# /etc/resolv.conf.tail can replace this line"
  fi
} > "$dest"
`;

const SYSTEMD_RESOLVED_STUB = "# This is /run/systemd/resolve/stub-resolv.conf\nnameserver 127.0.0.53\n";
const NETWORKMANAGER_RESOLV_CONF = "# Generated by NetworkManager\nnameserver 192.168.5.1\n";

let tmpRoot = "";
let sandboxBin = "";
let runIndex = 0;

// Resolve a host tool with the suite's own (real) PATH before the sandbox
// replaces it; a missing tool is a broken fixture, not a silent skip.
function resolveTool(tool: string): string {
  try {
    return execSync(`command -v ${tool}`, { encoding: "utf8" }).trim();
  } catch {
    throw new Error(`Fixture setup: host tool '${tool}' is required to run the devops scripts`);
  }
}

beforeAll(() => {
  tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "coffeemode-dns-fallback-"));
  sandboxBin = path.join(tmpRoot, "bin");
  fs.mkdirSync(sandboxBin);
  fs.mkdirSync(path.join(tmpRoot, "home"));
  for (const source of SCRIPT_SOURCES) {
    const target = path.join(tmpRoot, SCRATCH_ROOT, source);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(path.join(REPO_ROOT, source), target);
  }
  for (const tool of SANDBOX_TOOLS) {
    fs.symlinkSync(resolveTool(tool), path.join(sandboxBin, tool));
  }
  fs.writeFileSync(
    path.join(sandboxBin, "apt-get"),
    '#!/usr/bin/env bash\nprintf \'apt-get %s\\n\' "$*" >> "$STUB_LOG"\n',
    { mode: 0o755 },
  );
  fs.writeFileSync(
    path.join(sandboxBin, "id"),
    '#!/usr/bin/env bash\necho 0\n',
    { mode: 0o755 },
  );
  fs.writeFileSync(
    path.join(sandboxBin, "curl"),
    '#!/usr/bin/env bash\nprintf \'curl %s\\n\' "$*" >> "$STUB_LOG"\nprintf \'203.0.113.10\\n\'\n',
    { mode: 0o755 },
  );
  fs.writeFileSync(
    path.join(sandboxBin, "docker"),
    '#!/usr/bin/env bash\ncase "$*" in\n  --version) echo "Docker version 27.0.0-stub, build stub" ;;\n  info*) echo "active" ;;\n  *) echo "stub" ;;\nesac\n',
    { mode: 0o755 },
  );
});

afterAll(() => {
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

interface ScriptRun {
  status: number;
  output: string;
  invocations: string;
}

interface RunOptions {
  /** Scratch host tree the run is confined to; always required, never the real "/". */
  sysroot: string;
  /** Extra PATH entry in front of the sandbox (used to plant a `resolvconf`). */
  extraPath?: string;
}

function run(script: string, args: string[], options: RunOptions): ScriptRun {
  runIndex += 1;
  const logPath = path.join(tmpRoot, `invocations-${runIndex}.log`);
  fs.writeFileSync(logPath, "");
  const env: NodeJS.ProcessEnv = { ...process.env, SYSROOT: options.sysroot };
  env.PATH = [options.extraPath, sandboxBin].filter(Boolean).join(":");
  env.HOME = path.join(tmpRoot, "home");
  env.STUB_LOG = logPath;

  let status = 0;
  let output = "";
  try {
    output = execSync(`bash "${path.join(tmpRoot, script)}" ${args.join(" ")}`, {
      encoding: "utf8",
      env,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    const failure = error as { status?: number; stdout?: string; stderr?: string };
    status = failure.status ?? -1;
    output = `${failure.stdout ?? ""}${failure.stderr ?? ""}`;
  }
  return { status, output, invocations: fs.readFileSync(logPath, "utf8") };
}

interface HostFixture {
  root: string;
  resolvConf: string;
  tailFile: string;
  hook: string;
}

// Builds a scratch host tree. Defaults to the n150 shape: a dhcpcd-signed regular
// /etc/resolv.conf and the resolv.conf hook that appends /etc/resolv.conf.tail.
function makeHost(options: {
  resolvConf?: string | null;
  resolvConfSymlink?: string;
  /** Content written at the symlink target; null leaves the link dangling. */
  symlinkTargetContent?: string | null;
  tail?: string;
  hook?: string | null;
} = {}): HostFixture {
  const root = fs.mkdtempSync(path.join(tmpRoot, "host-"));
  const etc = path.join(root, "etc");
  fs.mkdirSync(etc, { recursive: true });
  const resolvConf = path.join(etc, "resolv.conf");
  const tailFile = path.join(etc, "resolv.conf.tail");
  const hook = path.join(root, "usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf");

  if (options.resolvConfSymlink) {
    // Relative targets keep the link inside the fixture; the path logic under
    // test is identical to the absolute links real hosts carry.
    fs.symlinkSync(options.resolvConfSymlink, resolvConf);
    if (options.symlinkTargetContent !== null) {
      const target = path.resolve(etc, options.resolvConfSymlink);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, options.symlinkTargetContent ?? SYSTEMD_RESOLVED_STUB);
    }
  } else if (options.resolvConf !== null) {
    fs.writeFileSync(
      resolvConf,
      options.resolvConf ?? `${DHCPCD_SIGNATURE}\nnameserver 192.168.5.1\n`,
    );
  }
  if (options.tail !== undefined) fs.writeFileSync(tailFile, options.tail);
  if (options.hook !== null) {
    fs.mkdirSync(path.dirname(hook), { recursive: true });
    fs.writeFileSync(
      hook,
      options.hook ??
        `# dhcpcd-base 10.1.0 resolv.conf hook\nif [ -f /etc/resolv.conf.tail ]; then\n\tcat /etc/resolv.conf.tail >> "$cf"\nfi\n`,
    );
  }
  return { root, resolvConf, tailFile, hook };
}

// The n150 outage shape: dhcpcd regenerated while the link was down, so the file
// carries dhcpcd's signature and the tail placeholder but no nameserver.
function outageResolvConf(): string {
  return `${DHCPCD_SIGNATURE}\n# /etc/resolv.conf.tail can replace this line\n`;
}

describe("Host DNS fallback (BRAWUKA-770)", () => {
  it("installs the fallback tail on a dhcpcd host without touching the live file", () => {
    const host = makeHost();
    const liveBefore = fs.readFileSync(host.resolvConf, "utf8");

    const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("dns-fallback: ok");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
    // The DHCP entries stay first and untouched: the fallback is appended to the
    // file dhcpcd regenerates, never written over the live resolver config.
    expect(fs.readFileSync(host.resolvConf, "utf8")).toBe(liveBefore);
  });

  it("is idempotent: a re-run appends nothing and preserves other tail entries", () => {
    const host = makeHost({ tail: "nameserver 9.9.9.9\n" });

    const first = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });
    const afterFirst = fs.readFileSync(host.tailFile, "utf8");
    const second = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });

    expect(first.status).toBe(0);
    expect(second.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(afterFirst);
    expect(afterFirst).toBe(`nameserver 9.9.9.9\n${FALLBACK_LINE}\n`);
    expect(second.output).toContain("already carries");
  });

  it("separates the fallback from a tail entry written without a final newline (BRAWUKA-777)", () => {
    // resolv.conf is line-oriented: appending straight onto an unterminated entry
    // fuses the two records, and the resolver then reads one bogus server.
    const host = makeHost({ tail: "nameserver 9.9.9.9" });

    const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });

    expect(result.status).toBe(0);
    const tail = fs.readFileSync(host.tailFile, "utf8");
    expect(tail).toBe(`nameserver 9.9.9.9\n${FALLBACK_LINE}\n`);
    expect(tail.split("\n").filter((line) => line.startsWith("nameserver"))).toEqual([
      "nameserver 9.9.9.9",
      FALLBACK_LINE,
    ]);
  });

  it("writes exactly one line into an empty tail file", () => {
    const host = makeHost({ tail: "" });

    const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
  });

  it("writes nothing under --dry-run", () => {
    const host = makeHost();

    const result = run(DNS_SCRIPT, ["apply", "--dry-run"], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("keeps the snapshot non-empty in the outage window that broke BRAWUKA-764", () => {
    // The incident shape: dhcpcd regenerates while the link is down, so the DHCP
    // block is empty. Without the tail the regenerated host file has no
    // nameserver at all, and any container created then snapshots that emptiness.
    const host = makeHost({ resolvConf: outageResolvConf() });
    const mirror = path.join(tmpRoot, "20-resolv.conf.mirror");
    fs.writeFileSync(mirror, DHCPCD_HOOK_MIRROR, { mode: 0o755 });

    // Control: no fallback installed yet — the failure mode is reproducible.
    execSync(`bash "${mirror}" "${host.resolvConf}" "" "${host.tailFile}"`);
    expect(fs.readFileSync(host.resolvConf, "utf8")).not.toContain("nameserver");

    const applied = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });

    // The live file is empty at this instant, so apply must not report ready:
    // a container created now would still snapshot an empty resolver set.
    expect(applied.status).toBe(1);
    expect(applied.output).toContain("dns-fallback: not-ready");
    expect(applied.output).toContain("recreate");
    // Ownership is confirmed dhcpcd here, so this host does get dhcpcd's own
    // regeneration command — the guidance is scoped, not removed (BRAWUKA-778).
    expect(applied.output).toContain("Regenerate now: dhcpcd");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);

    // Same empty DHCP block, but the tail now keeps the file usable — this is the
    // guarantee, proven through the hook's own assembly order.
    execSync(`bash "${mirror}" "${host.resolvConf}" "" "${host.tailFile}"`);
    expect(fs.readFileSync(host.resolvConf, "utf8")).toContain(FALLBACK_LINE);

    const checked = run(DNS_SCRIPT, ["check"], { sysroot: host.root });
    expect(checked.status).toBe(0);
    expect(checked.output).toContain("dns-fallback: ok");
  });

  it("reports a missing fallback as a failure, and passes once it is installed", () => {
    const host = makeHost();

    const before = run(DNS_SCRIPT, ["check"], { sysroot: host.root });
    expect(before.status).toBe(1);
    expect(before.output).toContain("dns-fallback: fail");
    expect(before.output).toContain("dns-fallback.sh apply");

    expect(run(DNS_SCRIPT, ["apply"], { sysroot: host.root }).status).toBe(0);

    const after = run(DNS_SCRIPT, ["check"], { sysroot: host.root });
    expect(after.status).toBe(0);
    expect(after.output).toContain("dns-fallback: ok");
    expect(after.output).toContain(FALLBACK_LINE);
  });

  it("fails the check while the live resolver file has no nameserver line", () => {
    // Tail installed, but the live file is still empty: a container created right
    // now would snapshot an empty upstream set, so the check must not pass.
    const host = makeHost({ resolvConf: outageResolvConf(), tail: `${FALLBACK_LINE}\n` });

    const result = run(DNS_SCRIPT, ["check"], { sysroot: host.root });

    expect(result.status).toBe(1);
    expect(result.output).toContain("dns-fallback: not-ready");
    expect(result.output).toContain("dhcpcd");
    // The operator distinction that cost the incident its 19h: recreate containers
    // that already snapshotted the broken set instead of waiting.
    expect(result.output).toContain("recreate");
  });

  it("does not touch a resolver file another manager owns (BRAWUKA-778)", () => {
    // The hook is installed, so the old evidence check said "applicable" — but
    // NetworkManager wrote this file, and dhcpcd never reads the tail for it.
    const host = makeHost({ resolvConf: NETWORKMANAGER_RESOLV_CONF });

    const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("dns-fallback: not-applicable");
    expect(result.output).toContain("signature");
    expect(result.output).not.toContain("Fallback active");
    expect(fs.existsSync(host.tailFile)).toBe(false);
    expect(fs.readFileSync(host.resolvConf, "utf8")).toBe(NETWORKMANAGER_RESOLV_CONF);
  });

  it("skips hosts whose resolver is not dhcpcd-managed, writing nothing", () => {
    const cases: Array<[string, HostFixture]> = [
      [
        "systemd-resolved stub symlink",
        makeHost({ resolvConfSymlink: "../run/systemd/resolve/stub-resolv.conf" }),
      ],
      ["no dhcpcd hook", makeHost({ hook: null })],
      [
        "dhcpcd hook that never reads the tail file",
        makeHost({
          hook: '#!/usr/bin/env bash\n# writes the DHCP nameservers and ignores any tail file\nprintf \'nameserver %s\\n\' "$new_domain_name_servers" > "$cf"\n',
        }),
      ],
    ];

    for (const [label, host] of cases) {
      const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });
      expect(result.status, label).toBe(0);
      expect(result.output, label).toContain("dns-fallback: not-applicable");
      expect(fs.existsSync(host.tailFile), label).toBe(false);
    }
  });

  it("skips a host where openresolv's resolvconf owns the resolver", () => {
    const host = makeHost();
    const bin = path.join(tmpRoot, "resolvconf-bin");
    fs.mkdirSync(bin, { recursive: true });
    fs.writeFileSync(path.join(bin, "resolvconf"), "#!/usr/bin/env bash\nexit 0\n", {
      mode: 0o755,
    });

    const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root, extraPath: bin });

    expect(result.status).toBe(0);
    expect(result.output).toContain("dns-fallback: not-applicable");
    expect(result.output).toContain("resolvconf");
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("reports not-ready when no live resolver file can be read at all", () => {
    // Nothing to append to and no way to prove dhcpcd ownership: the honest
    // answer is "not applicable, and this host cannot resolve right now".
    const cases: Array<[string, HostFixture]> = [
      [
        "dangling systemd-resolved symlink",
        makeHost({
          resolvConfSymlink: "../run/systemd/resolve/stub-resolv.conf",
          symlinkTargetContent: null,
        }),
      ],
      ["missing resolv.conf", makeHost({ resolvConf: null })],
      ["empty file another manager wrote", makeHost({ resolvConf: "# Generated by NetworkManager\n" })],
    ];

    for (const [label, host] of cases) {
      const result = run(DNS_SCRIPT, ["apply"], { sysroot: host.root });
      expect(result.status, label).toBe(1);
      expect(result.output, label).toContain("dns-fallback: not-ready");
      expect(result.output, label).toContain("recreate");
      // Recovery guidance follows the manager that owns the file: this script
      // confirmed none, so it points at that manager instead of naming a
      // command for one it only guessed at (BRAWUKA-778).
      expect(result.output, label).toContain("through whichever manager owns it");
      expect(result.output, label).not.toContain("Regenerate now: dhcpcd");
      expect(result.output, label).not.toContain("systemctl restart");
      expect(fs.existsSync(host.tailFile), label).toBe(false);
    }
  });

  it("attributes no recovery command to a manager that is merely installed (BRAWUKA-778)", () => {
    // The reviewer's combination: a NetworkManager-owned regular file plus a
    // `resolvconf` binary on PATH that nothing here uses. A binary's presence is
    // not ownership, so no resolvconf command may be suggested — apply and check
    // both point at the owning manager instead.
    const host = makeHost({ resolvConf: "# Generated by NetworkManager\n" });
    const bin = path.join(tmpRoot, "resolvconf-unused-bin");
    fs.mkdirSync(bin, { recursive: true });
    fs.writeFileSync(path.join(bin, "resolvconf"), "#!/usr/bin/env bash\nexit 0\n", {
      mode: 0o755,
    });

    for (const command of ["apply", "check"]) {
      const result = run(DNS_SCRIPT, [command], { sysroot: host.root, extraPath: bin });
      expect(result.status, command).toBe(1);
      expect(result.output, command).toContain("dns-fallback: not-ready");
      expect(result.output, command).toContain("through whichever manager owns it");
      expect(result.output, command).not.toContain("resolvconf -u");
      expect(result.output, command).not.toContain("Regenerate now: dhcpcd");
    }
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("gives the same manager-aware guidance from check (BRAWUKA-778)", () => {
    const host = makeHost({ resolvConf: "# Generated by NetworkManager\n" });

    const result = run(DNS_SCRIPT, ["check"], { sysroot: host.root });

    expect(result.status).toBe(1);
    expect(result.output).toContain("dns-fallback: not-ready");
    expect(result.output).toContain("through whichever manager owns it");
    expect(result.output).not.toContain("Regenerate now: dhcpcd");
  });

  it("does not promise a dhcpcd regeneration for a file another manager owns (BRAWUKA-778)", () => {
    const host = makeHost({ resolvConf: NETWORKMANAGER_RESOLV_CONF, tail: `${FALLBACK_LINE}\n` });

    const result = run(DNS_SCRIPT, ["revert"], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("was not touched by this script");
    expect(result.output).not.toContain("until dhcpcd regenerates it");
  });

  it("revert removes only the fallback line and stays idempotent", () => {
    const host = makeHost({ tail: `nameserver 9.9.9.9\n${FALLBACK_LINE}\n` });

    const first = run(DNS_SCRIPT, ["revert"], { sysroot: host.root });
    expect(first.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe("nameserver 9.9.9.9\n");

    const second = run(DNS_SCRIPT, ["revert"], { sysroot: host.root });
    expect(second.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe("nameserver 9.9.9.9\n");
  });

  it("revert deletes the tail file when it held nothing else", () => {
    const host = makeHost({ tail: `${FALLBACK_LINE}\n` });

    expect(run(DNS_SCRIPT, ["revert"], { sysroot: host.root }).status).toBe(0);
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("requires a command instead of guessing one", () => {
    const host = makeHost();

    const result = run(DNS_SCRIPT, [], { sysroot: host.root });

    expect(result.status).toBe(2);
    expect(result.output).toContain("apply");
    expect(result.output).toContain("check");
    expect(result.output).toContain("revert");
  });
});

describe("Provisioning contract for the DNS fallback (BRAWUKA-770)", () => {
  const PROVISION_ARGS = ["--skip-swap", "--skip-ufw", "--skip-fail2ban", "--skip-dokploy"];

  it("applies the fallback on a fresh host with no Docker installed", () => {
    const host = makeHost();

    const result = run(PROVISION_SCRIPT, ["--skip-docker", ...PROVISION_ARGS], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("Step 4/8");
    expect(result.output).toContain("Host DNS fallback: dns-fallback: ok");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
    // Nothing else on the host was touched: Docker is skipped, so its daemon
    // config and the live resolver file stay exactly as they were.
    expect(fs.existsSync(path.join(host.root, "etc/docker/daemon.json"))).toBe(false);
    expect(fs.readFileSync(host.resolvConf, "utf8")).not.toContain(FALLBACK_LINE);
  });

  it("applies the fallback on a host that already has Docker installed", () => {
    // The BRAWUKA-764 host: Docker was installed long before, so the installer's
    // own branch never ran — the guarantee must not live inside it.
    const host = makeHost();

    const result = run(PROVISION_SCRIPT, PROVISION_ARGS, { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("Docker is already installed");
    expect(result.output).toContain("Host DNS fallback: dns-fallback: ok");
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
    // An existing Docker install is never reinstalled: the branch that pulls
    // docker-ce from Docker's own repository must not run.
    expect(result.invocations).not.toContain("docker-ce");
  });

  it("re-running provisioning does not duplicate the fallback entry", () => {
    const host = makeHost();

    run(PROVISION_SCRIPT, PROVISION_ARGS, { sysroot: host.root });
    const afterFirst = fs.readFileSync(host.tailFile, "utf8");
    const second = run(PROVISION_SCRIPT, PROVISION_ARGS, { sysroot: host.root });

    expect(second.status).toBe(0);
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(afterFirst);
    expect(afterFirst.match(/nameserver 1\.1\.1\.1/g)).toHaveLength(1);
  });

  it("honours --skip-dns", () => {
    const host = makeHost();

    const result = run(PROVISION_SCRIPT, ["--skip-dns", ...PROVISION_ARGS], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("Host DNS fallback skipped (--skip-dns)");
    expect(result.output).toContain("Host DNS fallback: Skipped (--skip-dns)");
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });

  it("stops before creating anything while the host resolver is not ready (BRAWUKA-776)", () => {
    // The n150 window: Docker is installed and would snapshot an empty resolver
    // set into every container it creates, so provisioning must not reach the
    // container-creation steps.
    const host = makeHost({ resolvConf: outageResolvConf() });

    const result = run(PROVISION_SCRIPT, PROVISION_ARGS, { sysroot: host.root });

    expect(result.status).not.toBe(0);
    expect(result.output).toContain("dns-fallback: not-ready");
    expect(result.output).toContain("Refusing to continue");
    expect(result.output).not.toContain("Step 5/8");
    // The durable config still landed, so the host is one dhcpcd regeneration
    // away from being fixed — the abort is about container creation, not writes.
    expect(fs.readFileSync(host.tailFile, "utf8")).toBe(`${FALLBACK_LINE}\n`);
  });

  it("keeps a --dry-run rehearsal non-fatal on a host that is not ready", () => {
    const host = makeHost({ resolvConf: outageResolvConf() });

    const result = run(PROVISION_SCRIPT, ["--dry-run", ...PROVISION_ARGS], { sysroot: host.root });

    expect(result.status).toBe(0);
    expect(result.output).toContain("would stop provisioning");
    expect(fs.existsSync(host.tailFile)).toBe(false);
  });
});
