/**
 * Render the cafe-shell cache artifacts from the single source
 * (`web/config/app.yaml` → `seo.shellCache` → `web/lib/cache-policy.ts`):
 *
 *   - `deploy/dokploy/cache-rules.json` — the policy contract
 *     (`cafeShellCdnRules()`): what the shell cache MUST do, human/CI
 *     readable.
 *   - `deploy/dokploy/cloudflare-cache-rules.json` — the deployable edge
 *     ruleset (`cafeShellCloudflareRuleset()`): the exact payload
 *     `scripts/devops/apply-cache-rules.sh` PUTs to the zone (BRAWUKA-834).
 *     Generated, never hand-edited — the hand-maintained v7 payload drifted
 *     into a catch-all bypass that silently disabled the allow rule
 *     (BRAWUKA-836); drift checks + complement-by-construction prevent that.
 *
 * This file is the esbuild entry point bundled by
 * `scripts/generate-cache-rules.mjs` into `scripts/dist/` — the canonical TS
 * path is the only place the YAML→JSON mapping may live (BRAWUKA-821).
 */

import { cafeShellCdnRules, cafeShellCloudflareRuleset } from "@/lib/cache-policy";
import { loadYaml, parseAppConfig } from "@/lib/config-schema";

const CONTRACT_NOTE =
  "GENERATED by `npm run gen:cache-rules` (web/scripts/generate-cache-rules.mjs) " +
  "from web/config/app.yaml seo.shellCache via web/lib/cache-policy.ts " +
  "cafeShellCdnRules() — do not edit by hand; `npm run check:cache-rules` " +
  "fails on drift. Policy contract for the SSR /cafes/* shell " +
  "(BRAWUKA-184; locale bypass contract BRAWUKA-821).";

const RULESET_NOTE =
  "GENERATED by `npm run gen:cache-rules` from web/config/app.yaml " +
  "seo.shellCache via web/lib/cache-policy.ts cafeShellCloudflareRuleset() — " +
  "do not edit by hand; `npm run check:cache-rules` fails on drift. " +
  "Deployable Cloudflare ruleset bodies (zone cafemood.app, Free plan; " +
  "request phase http_request_cache_settings + response phase " +
  "http_response_cache_settings) applied by " +
  "scripts/devops/apply-cache-rules.sh (BRAWUKA-834; complement-fallback fix " +
  "BRAWUKA-836). Free-plan constraint: custom cache keys are unavailable, so " +
  "locale safety is enforced with bypass rules instead of cache-key inputs.";

/** Serialized contract artifact bytes (trailing newline, 2-space indent). */
export function renderCacheRulesJson(): string {
  const policy = parseAppConfig(loadYaml("app.yaml")).seo.shellCache;
  const rules = { $note: CONTRACT_NOTE, ...cafeShellCdnRules(policy) };
  return JSON.stringify(rules, null, 2) + "\n";
}

/** Serialized deployable ruleset bytes. */
export function renderCloudflareRulesJson(): string {
  const policy = parseAppConfig(loadYaml("app.yaml")).seo.shellCache;
  const payload = { $note: RULESET_NOTE, ...cafeShellCloudflareRuleset(policy) };
  return JSON.stringify(payload, null, 2) + "\n";
}
