/**
 * Render `deploy/dokploy/cache-rules.json` from the single source
 * (`web/config/app.yaml` → `seo.shellCache` → `cafeShellCdnRules()`).
 *
 * This file is the esbuild entry point bundled by
 * `scripts/generate-cache-rules.mjs` into `scripts/dist/` — the canonical TS
 * path is the only place the YAML→JSON mapping may live (BRAWUKA-821).
 */

import { cafeShellCdnRules } from "@/lib/cache-policy";
import { loadYaml, parseAppConfig } from "@/lib/config-schema";

const NOTE =
  "GENERATED by `npm run gen:cache-rules` (web/scripts/generate-cache-rules.mjs) " +
  "from web/config/app.yaml seo.shellCache via web/lib/cache-policy.ts " +
  "cafeShellCdnRules() — do not edit by hand; `npm run check:cache-rules` " +
  "fails on drift. Cloudflare edge cache rule for the SSR /cafes/* shell " +
  "(BRAWUKA-184; locale-cookie cache key added in BRAWUKA-821).";

/** Serialized artifact bytes (trailing newline, 2-space indent). */
export function renderCacheRulesJson(): string {
  const policy = parseAppConfig(loadYaml("app.yaml")).seo.shellCache;
  const rules = { $note: NOTE, ...cafeShellCdnRules(policy) };
  return JSON.stringify(rules, null, 2) + "\n";
}
