/** In-memory fakes for KV + D1 + fetch, matching the minimal structural types. */

import type { D1Like, D1PreparedLike, KVLike } from "../src/types";

export class FakeKV implements KVLike {
  private map = new Map<string, { value: string }>();
  lastTtl: number | undefined;

  async get(key: string): Promise<string | null> {
    return this.map.get(key)?.value ?? null;
  }

  async put(key: string, value: string, options?: { expirationTtl?: number }): Promise<void> {
    this.lastTtl = options?.expirationTtl;
    this.map.set(key, { value });
  }

  has(key: string): boolean {
    return this.map.has(key);
  }
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** LIKE → regex, honoring our escapeLike() backslash escapes. */
function likeToRegex(pat: string): RegExp {
  let re = "";
  for (let i = 0; i < pat.length; i++) {
    const c = pat[i];
    if (c === "\\" && i + 1 < pat.length) {
      re += escapeRegExp(pat[i + 1]);
      i++;
    } else if (c === "%") re += ".*";
    else if (c === "_") re += ".";
    else re += escapeRegExp(c);
  }
  return new RegExp(`^${re}$`, "i");
}

export class FakeD1 implements D1Like {
  rows: Array<Record<string, unknown>> = [];
  /** Number of batch() calls observed (atomic multi-upsert path). */
  batchCalls = 0;
  /** When set, run()/batch() reject to simulate storage outages. */
  failWrites = false;

  prepare(sql: string): D1PreparedLike {
    return new FakePrepared(this, sql);
  }

  async batch(statements: D1PreparedLike[]): Promise<Array<{ meta: { changes: number } }>> {
    this.batchCalls++;
    const results: Array<{ meta: { changes: number } }> = [];
    for (const s of statements) {
      results.push(await s.run());
    }
    return results;
  }
}

class FakePrepared implements D1PreparedLike {
  private binds: unknown[] = [];

  constructor(
    private db: FakeD1,
    private sql: string,
  ) {}

  bind(...values: unknown[]): D1PreparedLike {
    this.binds = values;
    return this;
  }

  async run(): Promise<{ meta: { changes: number } }> {
    if (this.db.failWrites) throw new Error("D1 simulated outage");
    if (this.sql.trimStart().startsWith("INSERT INTO pois")) {
      const [
        place_id, source, name, lat, lng, address,
        types, business_status, hours_json, photo_refs, fetched_at,
      ] = this.binds;
      const existing = this.db.rows.find((r) => r.place_id === place_id);
      const row = existing ?? {};
      Object.assign(row, {
        place_id, source, name, lat, lng, address,
        types, business_status, hours_json, photo_refs, fetched_at,
      });
      if (!existing) this.db.rows.push(row);
      return { meta: { changes: 1 } };
    }
    return { meta: { changes: 0 } };
  }

  async first<T = unknown>(): Promise<T | null> {
    return (this.evalSelect()[0] as T) ?? null;
  }

  async all<T = unknown>(): Promise<{ results: T[] }> {
    return { results: this.evalSelect() as T[] };
  }

  private evalSelect(): Array<Record<string, unknown>> {
    const whereMatch = this.sql.match(/WHERE (.+?)(?: ORDER BY|$)/);
    if (!whereMatch) return [...this.db.rows];
    // Conditions are generated by src/store.ts in fixed order (name, lat, lng, place_id),
    // all AND-ed. Resolve bind indices once per query — NOT inside the row filter
    // (filter runs per row, so a shared counter would over-consume binds).
    const where = whereMatch[1];
    let bi = 0;
    const pattern = where.includes("name LIKE ?") ? (this.binds[bi++] as string) : undefined;
    const latLo = where.includes("lat BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const latHi = where.includes("lat BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const lngLo = where.includes("lng BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const lngHi = where.includes("lng BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const placeId = where.includes("place_id = ?") ? (this.binds[bi++] as string) : undefined;
    const rows = this.db.rows.filter((row) => {
      if (pattern !== undefined && !likeToRegex(pattern).test(String(row.name))) return false;
      if (latLo !== undefined && !(Number(row.lat) >= latLo && Number(row.lat) <= latHi!)) return false;
      if (lngLo !== undefined && !(Number(row.lng) >= lngLo && Number(row.lng) <= lngHi!)) return false;
      if (placeId !== undefined && row.place_id !== placeId) return false;
      return true;
    });
    // Honor the generated LIMIT clause so result caps are testable.
    const limitMatch = this.sql.match(/LIMIT (\d+)/);
    return limitMatch ? rows.slice(0, Number(limitMatch[1])) : rows;
  }
}

export type FetchHandler = (
  url: string,
  init?: RequestInit,
) => Response | Promise<Response>;

export function mockFetch(handler: FetchHandler) {
  return async (url: string | URL | Request, init?: RequestInit): Promise<Response> =>
    handler(String(url), init);
}

export function googleDetailResponse(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    id: "ChIJTEST123",
    displayName: { text: "Blue Bottle Coffee" },
    formattedAddress: "66 Mint St, San Francisco, CA 94103",
    location: { latitude: 37.7825, longitude: -122.4077 },
    types: ["cafe", "coffee_shop"],
    businessStatus: "OPERATIONAL",
    regularOpeningHours: { periods: [] },
    photos: [{ name: "places/ChIJTEST123/photos/photo1" }],
    googleMapsUri: "https://maps.google.com/?cid=123",
    ...overrides,
  };
}