/** In-memory fakes for KV + D1 + fetch, matching the minimal structural types. */

import { kmPerDegLat, kmPerDegLng } from "../src/geo";
import type { D1Like, D1PreparedLike, KVLike } from "../src/types";

export class FakeKV implements KVLike {
  private map = new Map<string, { value: string }>();
  lastTtl: number | undefined;

  async get(key: string): Promise<string | null> {
    return this.map.get(key)?.value ?? null;
  }

  async put(key: string, value: string, options?: { expirationTtl?: number }): Promise<void> {
    this.lastTtl = options?.expirationTtl;
    this.map.set(key, { value });
  }

  async delete(key: string): Promise<void> {
    this.map.delete(key);
  }

  has(key: string): boolean {
    return this.map.has(key);
  }
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** LIKE → regex, honoring our escapeLike() backslash escapes. */
function likeToRegex(pat: string): RegExp {
  let re = "";
  for (let i = 0; i < pat.length; i++) {
    const c = pat[i];
    if (c === "\\" && i + 1 < pat.length) {
      re += escapeRegExp(pat[i + 1]);
      i++;
    } else if (c === "%") re += ".*";
    else if (c === "_") re += ".";
    else re += escapeRegExp(c);
  }
  return new RegExp(`^${re}$`, "i");
}

export class FakeD1 implements D1Like {
  rows: Array<Record<string, unknown>> = [];
  /** Number of batch() calls observed (atomic multi-upsert path). */
  batchCalls = 0;
  /** When set, run()/batch() reject to simulate storage outages. */
  failWrites = false;

  prepare(sql: string): D1PreparedLike {
    return new FakePrepared(this, sql);
  }

  async batch(statements: D1PreparedLike[]): Promise<Array<{ meta: { changes: number } }>> {
    this.batchCalls++;
    const results: Array<{ meta: { changes: number } }> = [];
    for (const s of statements) {
      results.push(await s.run());
    }
    return results;
  }
}

class FakePrepared implements D1PreparedLike {
  private binds: unknown[] = [];

  constructor(
    private db: FakeD1,
    private sql: string,
  ) {}

  bind(...values: unknown[]): D1PreparedLike {
    this.binds = values;
    return this;
  }

  async run(): Promise<{ meta: { changes: number } }> {
    if (this.db.failWrites) throw new Error("D1 simulated outage");
    if (this.sql.trimStart().startsWith("INSERT INTO pois")) {
      const [
        place_id, source, name, lat, lng, address,
        types, business_status, hours_json, fetched_at, expires_at,
      ] = this.binds;
      const existing = this.db.rows.find((r) => r.place_id === place_id);
      const row = existing ?? {};
      Object.assign(row, {
        place_id, source, name, lat, lng, address,
        types, business_status, hours_json, fetched_at, expires_at,
      });
      if (!existing) this.db.rows.push(row);
      return { meta: { changes: 1 } };
    }
    if (this.sql.trimStart().startsWith("DELETE FROM pois WHERE expires_at <=")) {
      const now = Date.now();
      const before = this.db.rows.length;
      this.db.rows = this.db.rows.filter((r) => {
        if (!r.expires_at) return true;
        const exp = Date.parse(r.expires_at as string);
        return Number.isNaN(exp) || exp > now;
      });
      return { meta: { changes: before - this.db.rows.length } };
    }
    return { meta: { changes: 0 } };
  }

  async first<T = unknown>(): Promise<T | null> {
    return (this.evalSelect()[0] as T) ?? null;
  }

  async all<T = unknown>(): Promise<{ results: T[] }> {
    return { results: this.evalSelect() as T[] };
  }

  private evalSelect(): Array<Record<string, unknown>> {
    const whereMatch = this.sql.match(/WHERE (.+?)(?: ORDER BY|$)/);
    if (!whereMatch) return [...this.db.rows];
    // Conditions are generated by src/store.ts in fixed order (name, lat, lng, place_id).
    // The lng condition may be an OR-ed pair of BETWEENs (antimeridian wrap).
    // Resolve bind indices once per query — NOT inside the row filter
    // (filter runs per row, so a shared counter would over-consume binds).
    const where = whereMatch[1];
    let bi = 0;
    const pattern = where.includes("name LIKE ?") ? (this.binds[bi++] as string) : undefined;
    const latLo = where.includes("lat BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const latHi = where.includes("lat BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    // Antimeridian wrap emits "(lng BETWEEN ? AND ? OR lng BETWEEN ? AND ?)"
    // with four binds (issue #38); check it before the plain two-bind form.
    const lngWrap = where.includes("OR lng BETWEEN ? AND ?");
    const lngLo = where.includes("lng BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const lngHi = where.includes("lng BETWEEN ? AND ?") ? (this.binds[bi++] as number) : undefined;
    const lngLo2 = lngWrap ? (this.binds[bi++] as number) : undefined;
    const lngHi2 = lngWrap ? (this.binds[bi++] as number) : undefined;
    const placeId = where.includes("place_id = ?") ? (this.binds[bi++] as number) : undefined;
    const rows = this.db.rows.filter((row) => {
      if (where.includes("expires_at >")) {
        if (row.expires_at) {
          const exp = Date.parse(row.expires_at as string);
          if (!Number.isNaN(exp) && exp <= Date.now()) return false;
        }
      }
      if (pattern !== undefined && !likeToRegex(pattern).test(String(row.name))) return false;
      if (latLo !== undefined && !(Number(row.lat) >= latLo && Number(row.lat) <= latHi!)) return false;
      if (lngLo !== undefined) {
        const v = Number(row.lng);
        const inFirst = v >= lngLo && v <= lngHi!;
        const inSecond = lngLo2 !== undefined && v >= lngLo2 && v <= lngHi2!;
        if (!inFirst && !inSecond) return false;
      }
      if (placeId !== undefined && row.place_id !== placeId) return false;
      return true;
    });
    // ORDER BY binds trail the WHERE binds. The distance proxy mirrors
    // store.ts: |dlat|*kmPerDegLat + min(|dlng|, 360-|dlng|)*kmPerDegLng —
    // without it the fake silently ignored ordering and the prefetch-cap
    // truncation was untestable (BRAWUKA-395 P2-3).
    const orderMatch = this.sql.match(/ORDER BY (.+?)(?: LIMIT|$)/);
    if (orderMatch) {
      const orderBy = orderMatch[1];
      if (orderBy.includes("MIN(ABS(lng")) {
        const cLat = this.binds[bi++] as number;
        const cLng = this.binds[bi++] as number;
        this.binds[bi++]; // lng bound twice in the SQL expression
        const latFactor = kmPerDegLat();
        const lngFactor = kmPerDegLng(cLat);
        const proxy = (row: Record<string, unknown>) => {
          const dLng = Math.abs(Number(row.lng) - cLng);
          return (
            Math.abs(Number(row.lat) - cLat) * latFactor + Math.min(dLng, 360 - dLng) * lngFactor
          );
        };
        rows.sort((a, b) => proxy(a) - proxy(b));
      } else if (orderBy.startsWith("name")) {
        rows.sort((a, b) => (String(a.name) < String(b.name) ? -1 : String(a.name) > String(b.name) ? 1 : 0));
      }
    }
    // Honor the generated LIMIT clause so result caps are testable.
    const limitMatch = this.sql.match(/LIMIT (\d+)/);
    return limitMatch ? rows.slice(0, Number(limitMatch[1])) : rows;
  }
}

export type FetchHandler = (
  url: string,
  init?: RequestInit,
) => Response | Promise<Response>;

export function mockFetch(handler: FetchHandler) {
  return async (url: string | URL | Request, init?: RequestInit): Promise<Response> =>
    handler(String(url), init);
}

export function googleDetailResponse(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    id: "ChIJTEST123",
    displayName: { text: "Blue Bottle Coffee" },
    formattedAddress: "66 Mint St, San Francisco, CA 94103",
    location: { latitude: 37.7825, longitude: -122.4077 },
    types: ["cafe", "coffee_shop"],
    businessStatus: "OPERATIONAL",
    regularOpeningHours: { periods: [] },
    googleMapsUri: "https://maps.google.com/?cid=123",
    ...overrides,
  };
}

/** One Autocomplete (New) suggestion, as the upstream returns it. */
export function autocompleteSuggestion(
  overrides: Record<string, unknown> = {},
): Record<string, unknown> {
  return {
    placePrediction: {
      placeId: "ChIJTEST123",
      text: { text: "Blue Bottle Coffee" },
      structuredFormat: {
        mainText: { text: "Blue Bottle Coffee" },
        secondaryText: { text: "Mint St, San Francisco" },
      },
      types: ["cafe", "coffee_shop"],
      ...overrides,
    },
  };
}