// Code generated by `scripts/generate-rate-limit-buckets.mjs` from
// `config/rate-limits.yaml` (BRAWUKA-625). DO NOT EDIT — add the bucket to
// the YAML and run `npm run gen:buckets`.
export const RATE_LIMIT_BUCKET_NAMES = [
  "cafes-read",
  "cafes-write",
  "images",
  "places",
  "places-autocomplete",
  "search",
  "profile-read",
  "profile-write",
  "profile-export",
  "identity-write",
  "onboarding",
  "heartbeat",
  "runtime-config",
  "health",
] as const;

export type RateLimitBucketName = (typeof RATE_LIMIT_BUCKET_NAMES)[number];
