#!/usr/bin/env bash
# ==============================================================================
# CafeMood Host DNS Upstream Fallback
# BRAWUKA-764 incident; BRAWUKA-770 contract; BRAWUKA-776/777/778 review findings
# Runbook: docs/devops/LIFECYCLE.md §6 "Host DNS Upstream Fallback"
#
# Why this exists
#   Docker snapshots the host /etc/resolv.conf into every container's embedded
#   resolver (127.0.0.11) at container-creation time, and it never refills a
#   running container after the host recovers. When dhcpcd regenerated
#   /etc/resolv.conf during the n150 WiFi outage with no DHCP nameserver, every
#   container created in that window was stuck on "NO EXTERNAL NAMESERVERS
#   DEFINED": staging deploys stopped for ~19h and the web→POI proxy answered
#   502. Owner decision (BRAWUKA-764 thread): keep DHCP nameservers first and
#   append 1.1.1.1 as a fallback — never replace the DHCP entries.
#
# What "applicable" means (BRAWUKA-778)
#   The tail is only written where the evidence says dhcpcd currently owns
#   /etc/resolv.conf:
#     1. /etc/resolv.conf is a regular file (not a symlink to a resolver stub),
#     2. no `resolvconf` binary is on PATH (dhcpcd delegates to it and never
#        reads the tail),
#     3. a dhcpcd hook exists that references /etc/resolv.conf.tail, and
#     4. the live file's first line is dhcpcd's own signature
#        (`# Generated by dhcpcd`, dhcpcd-run-hooks:7) — an installed hook alone
#        proves nothing about who writes the file now.
#   Anything else reports `not-applicable` and writes nothing, so another
#   manager's resolv.conf is never touched.
#
# What "ready" means (BRAWUKA-776)
#   Ready = the live /etc/resolv.conf carries at least one nameserver line, i.e.
#   a container created right now would snapshot a usable upstream set. Writing
#   the tail is durable configuration; it only reaches the live file at the next
#   dhcpcd regeneration. While the live file is empty, apply/check exit 1
#   (`not-ready`), print dhcpcd's regeneration command only where dhcpcd
#   ownership was confirmed and otherwise point at whichever manager owns the
#   file, and provisioning stops before it can create a container.
#
# Usage:
#   ./dns-fallback.sh apply [--dry-run]   # install the fallback, then report readiness
#   ./dns-fallback.sh check               # verify both, write nothing
#   ./dns-fallback.sh revert [--dry-run]  # remove the line this script added
#
# Options:
#   --dry-run   Evaluate and report without modifying system state
#   -h, --help  Show this help message and exit
#
# Environment:
#   SYSROOT   Root prefix for host paths (default: empty = the real "/"). The
#             fixture tests in web/tests/devops/dns-fallback.test.ts use it to
#             run this script against a scratch tree instead of the host.
#
# Exit codes:
#   0  ok          the fallback is installed (or not applicable here) and the
#                  live resolver file has at least one nameserver
#   1  not-ready   the live resolver file has no nameserver line (or is missing),
#                  so the fallback is not in effect and container creation must
#                  wait — with the remediation steps printed
#   2  usage error
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------------------
# Policy constants — the Owner-selected fallback resolver, and the signature
# dhcpcd writes as the first line of every /etc/resolv.conf it generates
# ------------------------------------------------------------------------------
FALLBACK_NAMESERVER="1.1.1.1"
FALLBACK_LINE="nameserver ${FALLBACK_NAMESERVER}"
DHCPCD_SIGNATURE='# Generated by dhcpcd'

# ------------------------------------------------------------------------------
# Host paths (SYSROOT-prefixed so fixture tests never touch the real host)
# ------------------------------------------------------------------------------
SYSROOT="${SYSROOT:-}"
SYSROOT="${SYSROOT%/}"
RESOLV_CONF="${SYSROOT}/etc/resolv.conf"
TAIL_FILE="${SYSROOT}/etc/resolv.conf.tail"
# dhcpcd ships its hooks in one of these locations depending on distro/version.
HOOK_CANDIDATES=(
  "${SYSROOT}/usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf"
  "${SYSROOT}/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf"
  "${SYSROOT}/etc/dhcpcd-hooks/20-resolv.conf"
)

# ------------------------------------------------------------------------------
# CLI Argument Parsing
# ------------------------------------------------------------------------------
DRY_RUN=false
COMMAND=""

show_help() {
  sed -n '2,/^# ==/p' "$0" | sed 's/^# \?//'
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      show_help
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    apply|check|revert)
      if [[ -n "$COMMAND" ]]; then
        echo "Error: command '${COMMAND}' already given (got '${1}' too)." >&2
        exit 2
      fi
      COMMAND="$1"
      shift
      ;;
    *)
      echo "Error: Unknown argument '$1'. Run '$0 --help' for usage." >&2
      exit 2
      ;;
  esac
done

if [[ -z "$COMMAND" ]]; then
  echo "Error: a command is required (apply | check | revert). Run '$0 --help'." >&2
  exit 2
fi

# ------------------------------------------------------------------------------
# Logging Utilities
# ------------------------------------------------------------------------------
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log()   { echo -e "${BOLD}${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${BOLD}${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${BOLD}${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${BOLD}${RED}[ERROR]${NC} $*" >&2; }

# The final line is the machine-readable status; provisioning summarises it.
status() { echo "dns-fallback: $1"; }

# ------------------------------------------------------------------------------
# Resolver ownership detection
# ------------------------------------------------------------------------------
# Sets MANAGER (`dhcpcd` or `other`) and REASON. Ownership is decided by evidence
# about who writes the file, and nothing else — a binary that happens to be
# installed, or a symlink target, is not proof that a manager is in use, so no
# recovery command is ever attributed to a manager this script did not confirm
# (BRAWUKA-778).
MANAGER="other"
REASON=""
HOOK_PATH=""

detect_manager() {
  if [[ -L "$RESOLV_CONF" ]]; then
    REASON="${RESOLV_CONF} is a symlink to $(readlink "$RESOLV_CONF" 2>/dev/null || echo '<unknown>') — managed by systemd-resolved, NetworkManager, or netplan, not dhcpcd"
    return 0
  fi

  if command -v resolvconf >/dev/null 2>&1; then
    REASON="a resolvconf binary is on PATH, so dhcpcd delegates to it and never appends ${TAIL_FILE}"
    return 0
  fi

  local candidate
  for candidate in "${HOOK_CANDIDATES[@]}"; do
    if [[ -f "$candidate" ]]; then
      HOOK_PATH="$candidate"
      break
    fi
  done

  if [[ -z "$HOOK_PATH" ]]; then
    REASON="no dhcpcd resolv.conf hook found (looked in ${HOOK_CANDIDATES[*]})"
    return 0
  fi

  if ! grep -q 'resolv\.conf\.tail' "$HOOK_PATH"; then
    REASON="dhcpcd hook ${HOOK_PATH} never references ${TAIL_FILE}, so the fallback would not reach the generated file"
    return 0
  fi

  # Ownership evidence: dhcpcd stamps its own signature as the first line of
  # every file it generates, including the ones it rebuilds with no nameserver.
  # Without it (file missing, truncated, or written by another manager) the
  # installed hook says nothing about who owns the file right now.
  if [[ ! -f "$RESOLV_CONF" ]]; then
    REASON="${RESOLV_CONF} does not exist, so dhcpcd ownership cannot be verified (check: head -n 1 ${RESOLV_CONF})"
    return 0
  fi

  if [[ "$(head -n 1 "$RESOLV_CONF" 2>/dev/null)" != "${DHCPCD_SIGNATURE}"* ]]; then
    REASON="${RESOLV_CONF} does not carry dhcpcd's signature '${DHCPCD_SIGNATURE}' on its first line, so another manager currently owns it (check: head -n 1 ${RESOLV_CONF})"
    return 0
  fi

  MANAGER="dhcpcd"
  REASON="dhcpcd owns ${RESOLV_CONF} (signature present) and hook ${HOOK_PATH} appends ${TAIL_FILE}"
}

# Print the interface whose DHCP lease owns /etc/resolv.conf, when discoverable.
detect_interface() {
  local iface=""
  if command -v ip >/dev/null 2>&1; then
    iface="$(ip route show default 2>/dev/null | awk 'NR==1 {print $5}' || true)"
  fi
  printf '%s' "$iface"
}

# The command that makes dhcpcd regenerate the live file. Only meaningful on a
# host where detect_manager confirmed dhcpcd ownership.
regenerate_hint() {
  local iface
  iface="$(detect_interface)"
  echo "dhcpcd ${iface:-<interface>}"
}

# ------------------------------------------------------------------------------
# Resolver file state
# ------------------------------------------------------------------------------
# Count `nameserver` lines in a resolv.conf-style file.
count_nameservers() {
  local file="$1"
  [[ -f "$file" ]] || { printf '0'; return 0; }
  grep -c '^[[:space:]]*nameserver[[:space:]]' "$file" || true
}

tail_has_fallback() {
  [[ -f "$TAIL_FILE" ]] || return 1
  grep -qx "[[:space:]]*${FALLBACK_LINE}[[:space:]]*" "$TAIL_FILE"
}

live_has_fallback() {
  [[ -f "$RESOLV_CONF" ]] || return 1
  grep -qx "[[:space:]]*${FALLBACK_LINE}[[:space:]]*" "$RESOLV_CONF"
}

# Live readiness: can a container created right now snapshot a usable upstream
# set? Sets LIVE_REASON either way.
LIVE_REASON=""
live_resolver_ready() {
  local count
  count="$(count_nameservers "$RESOLV_CONF")"
  if [[ "$count" -eq 0 ]]; then
    if [[ -f "$RESOLV_CONF" ]]; then
      LIVE_REASON="${RESOLV_CONF} has no nameserver line"
    else
      LIVE_REASON="${RESOLV_CONF} does not exist"
    fi
    return 1
  fi
  LIVE_REASON="${count} nameserver line(s) in ${RESOLV_CONF}"
  return 0
}

# Append the fallback line, preserving whatever the tail file already holds —
# including a last entry written without a final newline (BRAWUKA-777).
append_fallback_line() {
  mkdir -p "$(dirname "$TAIL_FILE")"
  if [[ ! -s "$TAIL_FILE" ]]; then
    printf '%s\n' "$FALLBACK_LINE" > "$TAIL_FILE"
    return 0
  fi
  if [[ -n "$(tail -c 1 "$TAIL_FILE")" ]]; then
    printf '\n' >> "$TAIL_FILE"
  fi
  printf '%s\n' "$FALLBACK_LINE" >> "$TAIL_FILE"
}

report_not_ready() {
  error "${LIVE_REASON} — a container created at this moment snapshots an empty upstream set."
  # A concrete command is given only for the manager this script confirmed:
  # dhcpcd. Every other host is told to recover through whichever manager owns
  # the file, because guessing one would be inventing a recovery step
  # (BRAWUKA-778).
  if [[ "$MANAGER" == "dhcpcd" ]]; then
    log "Regenerate now: $(regenerate_hint)   # then re-run: $0 check"
  else
    log "Regenerate ${RESOLV_CONF} through whichever manager owns it (this script does not write it), then re-run: $0 check"
  fi
  log "Containers already created keep their stale snapshot: recreate them (docker restart <name>, docker service update --force <service>) instead of waiting for the host to recover."
}

# ------------------------------------------------------------------------------
# apply
# ------------------------------------------------------------------------------
cmd_apply() {
  detect_manager

  if [[ "$MANAGER" == "dhcpcd" ]]; then
    log "Applicable: ${REASON}."
    if tail_has_fallback; then
      ok "${TAIL_FILE} already carries '${FALLBACK_LINE}' — leaving it untouched."
    elif [[ "$DRY_RUN" = true ]]; then
      ok "[DRY-RUN] Would append '${FALLBACK_LINE}' to ${TAIL_FILE} (existing entries preserved)."
    else
      append_fallback_line
      ok "Installed '${FALLBACK_LINE}' in ${TAIL_FILE} (existing entries preserved)."
    fi
  else
    warn "Not applicable on this host: ${REASON}."
    log "No fallback was written. See docs/devops/LIFECYCLE.md §6 before changing the host's resolver configuration by hand."
  fi

  # Live readiness decides whether provisioning may continue (BRAWUKA-776).
  if ! live_resolver_ready; then
    report_not_ready
    if [[ "$MANAGER" == "dhcpcd" ]]; then
      status "not-ready (${LIVE_REASON}; '${FALLBACK_LINE}' is installed in ${TAIL_FILE} and applies at the next dhcpcd regeneration)"
    else
      status "not-ready (${LIVE_REASON}; fallback does not apply here: ${REASON})"
    fi
    return 1
  fi

  if [[ "$MANAGER" == "dhcpcd" ]]; then
    if live_has_fallback; then
      ok "Fallback active in the live resolver file — containers created from now on snapshot it."
    else
      log "${RESOLV_CONF} has not picked up the fallback yet (it applies at the next dhcpcd regeneration)."
      log "To apply it now: $(regenerate_hint)"
    fi
    status "ok (fallback '${FALLBACK_LINE}' present in ${TAIL_FILE}; ${LIVE_REASON})"
  else
    status "not-applicable (${REASON}; ${LIVE_REASON})"
  fi
}

# ------------------------------------------------------------------------------
# check
# ------------------------------------------------------------------------------
cmd_check() {
  detect_manager

  if [[ "$MANAGER" == "dhcpcd" ]]; then
    log "Manager: dhcpcd — ${REASON}."
    if ! tail_has_fallback; then
      error "${TAIL_FILE} does not carry '${FALLBACK_LINE}'. The next dhcpcd regeneration can leave ${RESOLV_CONF} with no upstream resolver, and containers created in that window would snapshot an empty resolver set."
      log "Fix: $0 apply"
      status "fail (fallback missing from ${TAIL_FILE})"
      return 1
    fi
    ok "${TAIL_FILE} carries '${FALLBACK_LINE}'."
  else
    warn "Not applicable on this host: ${REASON}."
  fi

  if ! live_resolver_ready; then
    report_not_ready
    status "not-ready (${LIVE_REASON})"
    return 1
  fi
  ok "${LIVE_REASON}."

  if [[ "$MANAGER" == "dhcpcd" ]]; then
    if live_has_fallback; then
      ok "Fallback active in the live resolver file — containers created from now on snapshot it."
    else
      warn "Live ${RESOLV_CONF} has not picked up the fallback yet (it applies at the next dhcpcd regeneration)."
      log "To apply it now: $(regenerate_hint)"
    fi
    log "Reminder: a container created during an outage keeps its empty snapshot — recreate it rather than waiting."
    status "ok (fallback in ${TAIL_FILE}, ${LIVE_REASON})"
  else
    status "not-applicable (${REASON}; ${LIVE_REASON})"
  fi
}

# ------------------------------------------------------------------------------
# revert
# ------------------------------------------------------------------------------
cmd_revert() {
  detect_manager

  if [[ ! -f "$TAIL_FILE" ]]; then
    ok "${TAIL_FILE} does not exist — nothing to revert."
    status "ok (no fallback installed)"
    return 0
  fi

  if ! tail_has_fallback; then
    ok "${TAIL_FILE} carries no '${FALLBACK_LINE}' line — nothing to revert."
    status "ok (no fallback installed)"
    return 0
  fi

  if [[ "$DRY_RUN" = true ]]; then
    ok "[DRY-RUN] Would drop '${FALLBACK_LINE}' from ${TAIL_FILE} and delete the file if nothing else remains."
  else
    local tmp
    tmp="$(mktemp "${TAIL_FILE}.XXXXXX")"
    grep -vx "[[:space:]]*${FALLBACK_LINE}[[:space:]]*" "$TAIL_FILE" > "$tmp" || true
    if [[ -z "$(tr -d '[:space:]' < "$tmp")" ]]; then
      rm -f "$tmp" "$TAIL_FILE"
      ok "Removed ${TAIL_FILE} (it held only the fallback line)."
    else
      cat "$tmp" > "$TAIL_FILE"
      rm -f "$tmp"
      ok "Removed '${FALLBACK_LINE}' from ${TAIL_FILE}; other entries preserved."
    fi
  fi

  # The live file is only ever dhcpcd's to rebuild; on any other host this script
  # never wrote it, and naming a command for it would invent a recovery step.
  if [[ "$MANAGER" == "dhcpcd" ]]; then
    log "The live ${RESOLV_CONF} keeps the fallback until dhcpcd regenerates it: $(regenerate_hint)"
  else
    log "The live ${RESOLV_CONF} is not written by dhcpcd and was not touched by this script; recovery for it belongs to whichever tool owns it."
  fi
  status "ok (fallback removed)"
}

# ------------------------------------------------------------------------------
# Dispatch
# ------------------------------------------------------------------------------
case "$COMMAND" in
  apply)  cmd_apply ;;
  check)  cmd_check ;;
  revert) cmd_revert ;;
esac
